# Generated by Django 4.0.3 on 2022-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transação'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transação',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transação',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
    ]
