# Generated by Django 4.0.3 on 2022-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transação_options_alter_transação_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
